# ------------------------------

baseURL = "https://yuanfoudev.github.io/"
author = "yuanfou"
languageCode = "en"
DefaultContentLanguage = "zh"
paginate = 20
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = true

# ------------------------------

title = "元否的研究室"
theme = "paper"


[params]
  color = 'linen'
  twitter = 'yuanfoudev'
  
  #github = 'yuanfoudev'
  
  rss = true

  avatar = 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd6e23f4c-91f8-4665-8e2e-15eb24476d61%2Flogo.png?table=block&id=991a6272-a390-4ec7-8b93-1feb08e5054d&spaceId=6f061d15-8f2e-42d0-a148-068fb412b305&width=600&userId=5191ad45-3310-4476-a47f-6c90dded5c8a&cache=v2'
  name = '元否'
  bio = '未独立开发者|INTJ-A'

# ------------------------------


# 正确配置 markdown 解析设置，防止原始 html标签 被过滤。
defaultMarkdownHandler = 'goldmark'
[asciidocExt]
backend = 'html5'
extensions = []
failureLevel = 'fatal'
noHeaderOrFooter = true
preserveTOC = false
safeMode = 'unsafe'
sectionNumbers = false
trace = false
verbose = false
workingFolderCurrent = false
[asciidocExt.attributes]
[goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
typographer = true
[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
[goldmark.parser.attribute]
block = false
title = true
[goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
noHl = false
style = 'monokai'
tabWidth = 4
[tableOfContents]
endLevel = 3
ordered = false
startLevel = 2



# ------------------------------

# 配置网站菜单
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10
  [[menu.main]]
    identifier = "friends"
    name = "Friends"
    url = "/friends/"
    weight = 10

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"


# misc
  disableHLJS = true
  #gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTex math typesetting globally